# Generated by Django 4.1.2 on 2022-12-07 08:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0010_follow_author_alter_follow_following'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='follow',
            options={},
        ),
        migrations.RemoveField(
            model_name='follow',
            name='following',
        ),
    ]
